@baseUrl = http://localhost:3000

###

# Server: Main server
# Login/Sign-up UI
# This route serves the login/signup UI
GET {{baseUrl}}/ HTTP/1.1

###

# Server: Main server
# Register a new user
POST {{baseUrl}}/signup HTTP/1.1
Content-Type: application/json

{
  "email": "string@gmail.com",
  "password": "striaaaag",
  "requires2FA": true
}

###

# Server: Main server
# Authenticate user and return JWT
POST {{baseUrl}}/login HTTP/1.1
Content-Type: application/json

{
  "email": "string",
  "password": "string"
}

###

# Server: Main server
# Verify 2FA token
POST {{baseUrl}}/verify-2fa HTTP/1.1
Content-Type: application/json

{
  "email": "string",
  "loginAttemptId": "string",
  "2FACode": "string"
}

###

# Server: Main server
# Logout user
POST {{baseUrl}}/logout HTTP/1.1

###

# Server: Main server
# Verify JWT
# Verifies if a JWT is valid
POST {{baseUrl}}/verify-token HTTP/1.1
Content-Type: application/json

{
  "token": "string"
}
